# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ohlc_bars.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ohlc_bars.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fohlc_bars.proto\x12\tprotobars\"\x87\x01\n\x10IntradayOHLCBars\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\r\n\x05start\x18\x02 \x01(\t\x12\x18\n\x10volume_precision\x18\x03 \x01(\x05\x12\x17\n\x0fprice_precision\x18\x04 \x01(\x05\x12\"\n\x07\x63\x61ndles\x18\x05 \x03(\x0b\x32\x11.protobars.Candle\"\x87\x01\n\x0b\x45oDOHLCBars\x12\r\n\x05start\x18\x01 \x01(\t\x12\x18\n\x10volume_precision\x18\x02 \x01(\x05\x12\x17\n\x0fprice_precision\x18\x03 \x01(\x05\x12\"\n\x07\x63\x61ndles\x18\x04 \x03(\x0b\x32\x11.protobars.Candle\x12\x12\n\nnext_close\x18\x05 \x01(\t\"\x9f\x02\n\rOHLCBarResult\x12\x0c\n\x04zone\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x11\n\toffset_in\x18\x03 \x01(\t\x12G\n\x10intraday_candles\x18\x04 \x03(\x0b\x32-.protobars.OHLCBarResult.IntradayCandlesEntry\x12\x30\n\x0b\x65od_candles\x18\x05 \x01(\x0b\x32\x16.protobars.EoDOHLCBarsH\x00\x88\x01\x01\x1aS\n\x14IntradayCandlesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.protobars.IntradayOHLCBars:\x02\x38\x01\x42\x0e\n\x0c_eod_candles\"}\n\x06\x43\x61ndle\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\x0c\n\x04open\x18\x02 \x01(\x03\x12\x0c\n\x04high\x18\x03 \x01(\x03\x12\x0b\n\x03low\x18\x04 \x01(\x03\x12\r\n\x05\x63lose\x18\x05 \x01(\x03\x12\x0e\n\x06volume\x18\x06 \x01(\x03\x12\n\n\x02oi\x18\x07 \x01(\x03\x12\x0f\n\x07volume2\x18\x08 \x01(\x03\x42?Z=gocharting/gocharting-server-golang/proto/protobars;protobarsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ohlc_bars_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=gocharting/gocharting-server-golang/proto/protobars;protobars'
  _globals['_OHLCBARRESULT_INTRADAYCANDLESENTRY']._loaded_options = None
  _globals['_OHLCBARRESULT_INTRADAYCANDLESENTRY']._serialized_options = b'8\001'
  _globals['_INTRADAYOHLCBARS']._serialized_start=31
  _globals['_INTRADAYOHLCBARS']._serialized_end=166
  _globals['_EODOHLCBARS']._serialized_start=169
  _globals['_EODOHLCBARS']._serialized_end=304
  _globals['_OHLCBARRESULT']._serialized_start=307
  _globals['_OHLCBARRESULT']._serialized_end=594
  _globals['_OHLCBARRESULT_INTRADAYCANDLESENTRY']._serialized_start=495
  _globals['_OHLCBARRESULT_INTRADAYCANDLESENTRY']._serialized_end=578
  _globals['_CANDLE']._serialized_start=596
  _globals['_CANDLE']._serialized_end=721
# @@protoc_insertion_point(module_scope)
